<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="3" failed="0" total="3" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="12905" started-at="2021-12-28T14:24:45Z" finished-at="2021-12-28T14:24:58Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="12905" started-at="2021-12-28T14:24:45Z" finished-at="2021-12-28T14:24:58Z">
      <class name="com.blazeAutomation.UI.CreateBooking">
        <test-method status="FAIL" signature="launchApplication()[pri:0, instance:com.blazeAutomation.UI.CreateBooking@40a4337a]" name="launchApplication" is-config="true" duration-ms="0" started-at="2021-12-28T19:54:45Z" finished-at="2021-12-28T19:54:45Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Application launch failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Application launch failed
	at org.testng.Assert.fail(Assert.java:83)
	at com.blazeAutomation.UI.BaseTest.launchApplication(BaseTest.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:216)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:143)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:169)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
Caused by: java.lang.NullPointerException
	at java.util.Properties$LineReader.readLine(Properties.java:434)
	at java.util.Properties.load0(Properties.java:353)
	at java.util.Properties.load(Properties.java:341)
	at com.blazeAutomation.UI.ReadPropertyFile.readProperty(ReadPropertyFile.java:23)
	at com.blazeAutomation.UI.ReadPropertyFile.<init>(ReadPropertyFile.java:15)
	at com.blazeAutomation.UI.BaseTest.launchApplication(BaseTest.java:29)
	... 25 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method status="SKIP" signature="VerifyLoginPage()[pri:0, instance:com.blazeAutomation.UI.CreateBooking@40a4337a]" name="VerifyLoginPage" duration-ms="7" started-at="2021-12-28T19:54:58Z" description="Test to Purchase Flight" finished-at="2021-12-28T19:54:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyLoginPage -->
        <test-method status="SKIP" signature="verifyStatusCode_withInValidCityName()[pri:0, instance:com.blazeAutomation.UI.CreateBooking@40a4337a]" name="verifyStatusCode_withInValidCityName" duration-ms="6" started-at="2021-12-28T19:54:58Z" description="Verify API response when Invalid CITY Name: Tagla is given" finished-at="2021-12-28T19:54:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyStatusCode_withInValidCityName -->
        <test-method status="SKIP" signature="verifyStatusCode_withValidCityName()[pri:0, instance:com.blazeAutomation.UI.CreateBooking@40a4337a]" name="verifyStatusCode_withValidCityName" duration-ms="6" started-at="2021-12-28T19:54:58Z" description="Verify API response when valid CITY Name: Taglag is given" finished-at="2021-12-28T19:54:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyStatusCode_withValidCityName -->
        <test-method status="SKIP" signature="closeDriver()[pri:0, instance:com.blazeAutomation.UI.CreateBooking@40a4337a]" name="closeDriver" is-config="true" duration-ms="0" started-at="2021-12-28T19:54:58Z" finished-at="2021-12-28T19:54:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDriver -->
      </class> <!-- com.blazeAutomation.UI.CreateBooking -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
